### ISSUE TITLE
no dbdev extension after running install script

### ISSUE THREAD

**Issue by logemann** [supabase/dbdev#177]
# Bug report

## Describe the bug

after running the install script as outlined here:
https://database.dev/supabase/dbdev
on supabase cloud, i cant find the extension in the extensions overview. Script ran w/o problems though.

Of course i also cant do: select * from dbdev('kiwicopple-pg_idkit') 

```
ERROR:  42883: function dbdev(unknown) does not exist
LINE 1: select * from dbdev('kiwicopple-pg_idkit');
                      ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts. 
```

I am also puzzled of the install script using pg_tle while tle is not being available in supabase cloud.

## Expected behavior

a running package manager client.

**Comment by imor** [comment]
Extensions installed using dbdev are not visible on the extensions page because they are [trusted language extensions](https://github.com/aws/pg_tle?tab=readme-ov-file#trusted-language-extensions-for-postgresql-pg_tle). You can view them with the following sql:

```sql
select * from pgtle.available_extensions();
```

The complete pg_tle api is documented here: https://github.com/aws/pg_tle/blob/main/docs/03_managing_extensions.md.

`pg_tle` is also not visible on the dashboard but is available. As per the [installation instructions](https://github.com/aws/pg_tle/blob/main/docs/01_install.md) it needs to be set in `shared_preload_libraries`, so you can see it is set by running:

```sql
show shared_preload_libraries;
```

**Comment by logemann** [comment]
But can you comment on the real error then? Its nice to know that i cant see the extensions but this doesnt explain my error

**Comment by logemann** [comment]
as written in my bug report, i ran the install script as outlined https://database.dev/supabase/dbdev

According to the documentation i should be able to install extensions then. So i went ahaed and tried the docs outlined for idkit: https://github.com/kiwicopple/pg-extensions/tree/main/pg_idkit

Thats also the place where i got this command from:
select * from dbdev('kiwicopple-pg_idkit')

So your documentation seems of in various places...

**Comment by imor** [comment]
It is available in the cloud, but something might be wrong with your project. Please raise a support ticket to get someone to take a look.
